sudo: required

services:
  - docker

before_install:
  - docker build -t cosmos91/test-docker-react  -f Dockerfile.dev .

script:
  - docker run cosmos91/test-docker-react npm run test -- --coverage
