language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t cosmos91/test-docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true cosmos91/test-docker-react npm run test
